server:
  port: 82

dbServer:
  default: localhost:3306
  read: localhost:3306
  write: localhost:3306

datasource:
  default:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: default
    continue-on-error: false
    jdbc-url: jdbc:mysql://${dbServer.default}/quartz?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    connection-timeout: 30000
    connection-test-query: SELECT 1
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 600000
    destroy-method: shutdown
    auto-commit: false
  read:
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: default
      continue-on-error: false
      jdbc-url: jdbc:mysql://${dbServer.read}/quartz?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      connection-timeout: 30000
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 600000
      destroy-method: shutdown
      auto-commit: false
  write:
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: default
      continue-on-error: false
      jdbc-url: jdbc:mysql://${dbServer.write}/quartz?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      connection-timeout: 30000
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 600000
      destroy-method: shutdown
      auto-commit: false

mybatis:
  mapperLocations: classpath:mybaties/quartz/**/*Mapper.xml
  configLocation: classpath:mybaties/mybaties-config.xml